/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaplibreRouteImport } from './routes/maplibre'
import { Route as ReactMapGlRouteImport } from './routes/react-map-gl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaplibreRoute = MaplibreRouteImport.update({
  id: '/maplibre',
  path: '/maplibre',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactMapGlRoute = ReactMapGlRouteImport.update({
  id: '/react-map-gl',
  path: '/react-map-gl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maplibre': typeof MaplibreRoute
  '/react-map-gl': typeof ReactMapGlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maplibre': typeof MaplibreRoute
  '/react-map-gl': typeof ReactMapGlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maplibre': typeof MaplibreRoute
  '/react-map-gl': typeof ReactMapGlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maplibre' | '/react-map-gl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maplibre' | '/react-map-gl'
  id: '__root__' | '/' | '/maplibre' | '/react-map-gl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaplibreRoute: typeof MaplibreRoute
  ReactMapGlRoute: typeof ReactMapGlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maplibre': {
      id: '/maplibre'
      path: '/maplibre'
      fullPath: '/maplibre'
      preLoaderRoute: typeof MaplibreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-map-gl': {
      id: '/react-map-gl'
      path: '/react-map-gl'
      fullPath: '/react-map-gl'
      preLoaderRoute: typeof ReactMapGlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaplibreRoute: MaplibreRoute,
  ReactMapGlRoute: ReactMapGlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
