import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { EliContinent, EliDetailsShard, EliGeometries, EliManifest } from '../src/core/types'
import { fetchEliSourceCommit } from './eli-github'
import { fetchEli } from './fetch'
import { transform } from './transform'

const DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'data')

/** Stable JSON output: sorted keys so regenerated files diff only on real changes. */
function stableStringify(value: unknown): string {
  return `${JSON.stringify(value, replacer, 2)}\n`
}

function replacer(_key: string, value: unknown): unknown {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)),
    )
  }
  return value
}

function nonEmptyShards<T extends Record<string, unknown>>(
  byContinent: Record<EliContinent, T>,
): [EliContinent, T][] {
  return (Object.entries(byContinent) as [EliContinent, T][]).filter(
    ([, shard]) => Object.keys(shard).length > 0,
  )
}

async function readExisting(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return null
  }
}

/** True when payload differs from the file on disk (missing file → changed). */
async function needsWrite(path: string, contents: string): Promise<boolean> {
  const existing = await readExisting(path)
  return existing !== contents
}

export async function buildData(): Promise<EliManifest> {
  console.log('Fetching Editor Layer Index…')
  const { raw, source, sourceVersion } = await fetchEli()

  console.log('Resolving upstream commit…')
  let sourceCommit: string | null = null
  try {
    sourceCommit = await fetchEliSourceCommit()
  } catch (error) {
    console.warn('Could not resolve ELI sourceCommit (continuing):', error)
  }

  console.log('Validating + transforming…')
  const {
    locatorLayers,
    detailsByContinent,
    geometriesByContinent,
    shardsMeta,
    byCountry,
    apiKeys,
    counts,
  } = transform(raw)

  const detailShards = nonEmptyShards(detailsByContinent)
  const geometryShards = nonEmptyShards(geometriesByContinent)

  const previousManifest = await readExisting(join(DATA_DIR, 'manifest.json')).then((rawJson) => {
    if (!rawJson) return null
    try {
      return JSON.parse(rawJson) as EliManifest
    } catch {
      return null
    }
  })

  const manifestBase = {
    source,
    sourceVersion,
    sourceCommit,
    counts: {
      ...counts,
      detailShards: detailShards.length,
      geometryShards: geometryShards.length,
    },
  }

  // Generated TS so the set of API-key names is a typed union for consumers.
  const apiKeysModule =
    `// GENERATED by scripts/build-data.ts — do not edit.\n` +
    `// API-key placeholder names found across ELI layer tile URLs.\n` +
    `export const ELI_API_KEYS = ${JSON.stringify(apiKeys)} as const\n`

  const detailsDir = join(DATA_DIR, 'details')
  const geometriesDir = join(DATA_DIR, 'geometries')

  await mkdir(detailsDir, { recursive: true })
  await mkdir(geometriesDir, { recursive: true })

  const planned: { path: string; contents: string }[] = [
    { path: join(DATA_DIR, 'locator.json'), contents: stableStringify({ layers: locatorLayers }) },
    { path: join(DATA_DIR, 'shards.json'), contents: stableStringify(shardsMeta) },
    { path: join(DATA_DIR, 'byCountry.json'), contents: stableStringify(byCountry) },
    { path: join(DATA_DIR, 'apiKeys.ts'), contents: apiKeysModule },
    ...detailShards.map(([continent, shard]: [EliContinent, EliDetailsShard]) => ({
      path: join(detailsDir, `${continent}.json`),
      contents: stableStringify(shard),
    })),
    ...geometryShards.map(([continent, shard]: [EliContinent, EliGeometries]) => ({
      path: join(geometriesDir, `${continent}.json`),
      contents: stableStringify(shard),
    })),
  ]

  const contentChanged = (
    await Promise.all(planned.map(async (file) => needsWrite(file.path, file.contents)))
  ).some(Boolean)

  const provenanceChanged =
    previousManifest?.source !== source ||
    previousManifest?.sourceVersion !== sourceVersion ||
    previousManifest?.sourceCommit !== sourceCommit ||
    JSON.stringify(previousManifest?.counts) !== JSON.stringify(manifestBase.counts)

  // Avoid weekly no-op releases from `generatedAt` churn alone.
  if (!contentChanged && !provenanceChanged && previousManifest) {
    console.log(
      `No ELI data changes (${counts.published}/${counts.upstream} layers); leaving files untouched.`,
    )
    return previousManifest
  }

  const manifest: EliManifest = {
    ...manifestBase,
    // `new Date()` is fine here — this script runs in Bun/Node, not in a workflow sandbox.
    generatedAt: new Date().toISOString(),
  }

  await Promise.all([
    ...planned.map((file) => writeFile(file.path, file.contents)),
    writeFile(join(DATA_DIR, 'manifest.json'), stableStringify(manifest)),
  ])

  // Drop legacy monoliths once continent shards are written.
  await Promise.all(
    ['index.json', 'geometries.json'].map(async (file) => {
      try {
        await unlink(join(DATA_DIR, file))
      } catch {
        // Already absent — fine.
      }
    }),
  )

  console.log(
    `Wrote ${counts.published}/${counts.upstream} layers, ${counts.geometries} unique geometries, ` +
      `${detailShards.length} detail shards, ${geometryShards.length} geometry shards` +
      (sourceCommit ? ` @ ${sourceCommit.slice(0, 7)}` : '') +
      '.',
  )
  if (Object.keys(counts.dropped).length) {
    console.log(`Dropped unsupported types: ${JSON.stringify(counts.dropped)}`)
  }
  return manifest
}

if (import.meta.main) {
  await buildData()
}
